secrets:
  nostr_keys:
    file: ../nsec_keys.txt

services:
  yearprogress-boot:
    image: yearprogress-boot
    container_name: yearprogress-boot
    build:
      context: ./.
      dockerfile: ./Dockerfile
    working_dir: /yearprogress-boot
    volumes:
      - .:/yearprogress-boot:cached
    environment:
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - NOSTR_RELAYS=wss://nos.lol;wss://nostr.mom;wss://relay.damus.io;wss://offchain.pub;wss://relay.snort.social
      - TZ=America/Sao_Paulo
    tty: true
    secrets:
      - nostr_keys
