version: '3.9'

secrets:
  nostr_keys:
    file: ../nsec_keys.txt

services:
  yearprogress-boot:
    image: yearprogress-boot
    container_name: yearprogress-boot
    build:
      context: ./.
      dockerfile: ./Dockerfile
    working_dir: /yearprogress-boot
    volumes:
      - .:/yearprogress-boot:cached
    environment:
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - NOSTR_RELAYS=wss://nostr.rocks;wss://relay.nostr.ch;wss://relay.mostr.pub;wss://nostr-pub.wellorder.net;wss://nostr.bitcoiner.social;wss://nostr.inosta.cc;wss://nostr.milou.lol;wss://nostr.frennet.xyz
      - TZ=America/Sao_Paulo
    tty: true
    secrets:
      - nostr_keys