secrets:
  nostr_keys:
    file: nsec_keys_dev.txt

services:
  yearprogress-dev:
    image: yearprogress-dev
    container_name: yearprogress-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /yearprogress
    volumes:
      - ..:/yearprogress:cached
    environment:
      - NOSTR_PRIVATE_KEY_FILE=/run/secrets/nostr_keys
      - NOSTR_RELAYS=wss://nostr.rocks;wss://relay.nostr.ch;wss://relay.mostr.pub;wss://nostr-pub.wellorder.net;wss://nostr.bitcoiner.social;wss://nostr.inosta.cc;wss://nostr.milou.lol;wss://nostr.frennet.xyz
      - TZ=America/Sao_Paulo
    tty: true
    secrets:
      - nostr_keys
