version: '3.9'

secrets:
  nostr_keys:
    file: ../nsec_keys.txt

services:
  nostrboot:
    image: nostrboot
    container_name: nostrboot
    #user: nostrbot
    build:
      context: ./.
      dockerfile: ./Dockerfile
    working_dir: /nostrboot
    volumes:
      - .:/nostrboot:cached
    environment:
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - NOSTR_RELAYS=wss://relay.nostrica.com;wss://nostr.plebchain.org;wss://relay.nostriches.org;wss://bitcoiner.social;wss://relay.nostrplebs.com;wss://nostr.rocks;wss://nostr.relayer.se;wss://relay.nostr.ch;wss://nostr.sandwich.farm;wss://relay.mostr.pub;wss://nostr-pub.wellorder.net;wss://relay.snort.social;wss://nostr.bitcoiner.social;wss://nostr.inosta.cc;wss://puravida.nostr.land;wss://atlas.nostr.land;wss://nostr.milou.lol;wss://brb.io;wss://nostr.zebedee.cloud;wss://nostr.frennet.xyz
      - TZ=America/Sao_Paulo
    tty: true
    secrets:
      - nostr_keys